### ISSUE TITLE
LinearSystem implementation is incomplete

### ISSUE THREAD

**Issue by Woz4tetra** [robotpy/robotpy-wpimath#44]
### Problem description

There is a limited number of options for LinearSystem and subsequent required objects. My system has 3 states and 2 inputs. This is not an available option. Is it feasible to make the number of states and inputs configurable at run time like Java and C++ do at compile time?

For reference this is the code I'm trying to copy over:
https://github.com/frc-88/DiffyJrROS/blob/78019a034a5ad7bcd59af6932be216159df703dd/src/main/java/frc/robot/util/diffswerve/DiffSwerveModule.java#L133

### Operating System

Windows, MacOS, Linux, RoboRIO, Raspbian

**Comment by virtuald** [comment]
It is not feasible to make the number of states and inputs configurable at run time like Java does, we can only do it at compile time because we are wrapping C++.

For LinearSystem and friends, since it wasn't clear which state/input combinations were needed, I elected to use the ones that the wpilibc unit/integration tests were using at the time, or that other elements of WPILib needed defined.

I'm happy to add more combinations and push an updated release this evening if you tell me which combinations for particular objects that you need -- or you can make the PR yourself. The configuration is in the "templates" section of the yaml files in the gen directory. For example, the LinearSystem configuration can be found at https://github.com/robotpy/robotpy-wpimath/blob/4142ecef8a1845ec054ce539f8d33e245b33ac84/gen/controls/LinearSystem.yml#L32

**Comment by Woz4tetra** [comment]
The system I have has 3 states and 2 inputs, so I believe the LinearSystem and related objects would be called LinearSystem_3_2_3.

Do you foresee anyway this can be changed in the future?

**Comment by Woz4tetra** [comment]
Alternatively, what is the best way for me to build this library locally in case I'm testing a new system with a different state configuration?

**Comment by Woz4tetra** [comment]
Here's the object names I need:
```python
from wpimath.system import LinearSystem_3_2_3 as LinearSystem
from wpimath.system import LinearSystemLoop_3_2_3 as LinearSystemLoop
from wpimath.estimator import KalmanFilter_3_2_3 as KalmanFilter
from wpimath.controller import LinearQuadraticRegulator_3_2 as LinearQuadraticRegulator
```

**Comment by Woz4tetra** [comment]
PR is here: https://github.com/robotpy/robotpy-wpimath/pull/45

**Comment by virtuald** [comment]
Building the library locally is a bit of a challenge. Unless you want to build all of robotpy, you need to use the same platforms and compilers that we use in CI as slight differences in compilers can cause errors -- but in theory, you can use `setup.py` in all of our projects the same way one would build any python project.

**Comment by virtuald** [comment]
Also, if you don't want to build your own wheels, it is worth noting that when you make a PR, if it finishes successfully the built wheels are published as an artifact that you can download from github actions.

**Comment by Woz4tetra** [comment]
That fix worked! Thanks so much. I'm not seeing any typing errors.
I'm having memory error issues now but I think that's related to this old roborio I'm testing on.

**Comment by virtuald** [comment]
Certain types of errors in the C++ code or the wrapper code will manifest as memory related crashes (on Linux, anything that has "glibc detected" in it might be this sort of error). For example, https://github.com/wpilibsuite/allwpilib/pull/5138 presented as a memory-related segfault but it was just a bug. If you can isolate any issues to particular components, happy to take a deeper look at it.
